### ISSUE TITLE
Maven is missing jar starting version 4.0.0

### ISSUE THREAD

**Issue by gupta-ankit** [DSpace/xoai#43]
The latest version (4.1.0) of XOAI starting 4.0.0 is not available on Maven central. It shows an entry but does show actually have the jar file.

If I create a maven/gradle project with xoai dependency 4+, no library gets downloaded

http://mvnrepository.com/artifact/com.lyncode/xoai/4.1.0

Can you please check?

**Comment by mmalmeida** [comment]
@gupta-ankit  I believe the XOAI project is the parent project, which is just a POM with information.

You should import one of the modules (e.g xoai-data-provider or xoai-service-provider) depending on your needs.

Let me know if you still have issues.

**Comment by mmalmeida** [comment]
I propose closing this ticket.
