### ISSUE TITLE
Sets are added to an item independently from the filter

### ISSUE THREAD

**Issue by christian-scheible** [DSpace/xoai#45]
If an oai context contains for example 2 virtual sets. 
S1. Items with dc.identifier.doi
S2. Items without dc.identifier.doi
and wie have 2 Items:
A with doi
B without doi 
then as expected:
S1 only contains item A
S2 only contains item B 
But if you look at Item A with GetRecord than the record shows that the item is part of S1 and S2 which is false.
This is due to a bug in version 3.2.9 of the xoai library:
https://github.com/lyncode/xoai/blob/xoai-3.2.9/src/main/java/com/lyncode/xoai/dataprovider/data/internal/ItemIdentifyHelper.java#L23
It add's a set to an item independent of the filter.

**Comment by tdonohue** [comment]
This was fixed by #47. Closing this ticket. The fix will be released in upcoming 3.2.10
