### ISSUE TITLE
Allow setting the User Agent in HTTP requests

### ISSUE THREAD

**Issue by mdcarreira** [DSpace/xoai#61]
Some repositories will return a HTTP 403 Forbidden when HttpOAIClient tries to execute requests. This occurs because the User Agent property is not properly configured.

Therefore, to avoid this issue, HttpOAIClient should allow changing the User Agent.

Example of OAI repository where this error occurs: http://repositorio.insa.pt/oaiextended/request

**Comment by mmalmeida** [comment]
@mdcarreira could you send your pull request for this one please?
